<?php

$storename = Mage::app()->getStore();
$www = Mage::app()->getWebsite();
$websiteId = $www->getId();
 
$firstName = 'Syed';
$lastName = 'Warsi';
$email = 'sswarsi@hotmail.com.com';
$logFileName = 'customer.log';
 
$address = array(
            'customer_address_id' => '',
            'prefix' => '',
            'firstname' => $firstName,
            'middlename' => '',
            'lastname' => $lastName,
            'suffix' => '',
            'company' => '', 
            'street' => array(
                 '0' => 'Your Customer Address 1', // Manadotery
                 '1' => 'Your Customer Address 2' // optional
             ),
            'city' => 'stoke on trent',
            'country_id' => 'UK', // two letters country code
            'region' => 'Staffordshire', // region
            'region_id' => '11', // region_id
            'postcode' => 'st1',
            'telephone' => '01782',
            'fax' => '',
            'save_in_address_book' => 1
        );
 
// check if the email address is already registered
$customer = Mage::getModel('customer/customer')
                ->setWebsiteId($websiteId)
                ->loadByEmail($email);
 

if ($customer->getId()) {        
    Mage::log('Customer with email '.$email.' is already registered.', null, $logFileName);
    
    if( !Mage::getSingleton('customer/session')->isLoggedIn() ) {             
        
        Mage::app()->getResponse()
                   ->setRedirect(Mage::getUrl('customer/account/login'))
                   ->sendResponse();
            
    } else {         
        Mage::app()->getResponse()
                   ->setRedirect(Mage::getUrl('customer/account'))
                   ->sendResponse();
    }
        
} else {    
    $customer = Mage::getModel('customer/customer');
    
    $password = $customer->generatePassword(); // custom password
    
    $customer->setWebsiteId($websiteId)
             ->setStore($storename)
             ->setFirstname($firstName)
             ->setLastname($lastName)
             ->setEmail($email)
             ->setPassword($password);
                                
    try {
        // set the customer as confirmed
        $customer->setForceConfirmed(true);
        
        // save customer
        $customer->save();
        
        $customer->setConfirmation(null);
        $customer->save();
        
        // set customer address
        $customerId = $customer->getId();        
        $customAddress = Mage::getModel('customer/address');            
        $customAddress->setData($address)
                      ->setCustomerId($customerId)
                      ->setIsDefaultBilling('1')
                      ->setIsDefaultShipping('1')
                      ->setSaveInAddressBook('1');
        
        // save customer address
        $customAddress->save();
        
        // send new account email to customer    
        $storeId = $customer->getSendemailStoreId();
        $customer->sendNewAccountEmail('registered', '', $storeId);
        
        // set password remainder email if the password is auto generated by magento
        $customer->sendPasswordReminderEmail();
                
        Mage::log('Customer with email '.$email.' is successfully created.', null, $logFileName);
        
        echo 'Customer with email '.$email.' is successfully created. <br />';
        
    } catch (Mage_Core_Exception $e) {
        if (Mage::getSingleton('customer/session')->getUseNotice(true)) {
            Mage::getSingleton('customer/session')->addNotice(Mage::helper('core')->escapeHtml($e->getMessage()));
        } else {
            $messages = array_unique(explode("\n", $e->getMessage()));
            foreach ($messages as $message) {
                Mage::getSingleton('customer/session')->addError(Mage::helper('core')->escapeHtml($message));
            }
        }
    } catch (Exception $e) {
        
        Mage::getSingleton('customer/session')->addException($e, $this->__('Cannot add customer'));
        Mage::logException($e);
    } 
}

?>
